- hosts: "{{ env }}"
  become: yes
  tasks: 
     - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
     - name: Start the container
      docker_container:
        name: projcert
        image: "joemile/projcert:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080
   
